[package]
name = "benchmarks"
version = "0.1.0"
authors = ["Shinmera <shinmera@tymoon.eu>"]

[dependencies]
rdkafka = "*"
timely = "*"
timely_communication = "*"
abomonation = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
rand = "*"
uuid = { version = "*", features = ["v4"] }

[dependencies.kafkaesque]
git = "https://github.com/frankmcsherry/timely-dataflow.git"
